### ISSUE TITLE
git Clone failed - is this repo private?

### ISSUE THREAD

**Issue by LeeYangLBLBCS** [epics-modules/dxpSITORO#6]
~/temp$ git clone git@github.com:epics-modules/dxpSITORO.git
Cloning into 'dxpSITORO'...
The authenticity of host 'github.com (140.82.112.3)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.112.3' (ECDSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by MarkRivers** [comment]
This looks like a problem with your ssh public key. Try cloning with https.

**Comment by LeeYangLBLBCS** [comment]
I thougtht the latest clone will fix this compile error. But it didn't.
**../../../dxpApp/handel/src/handel_md_threads_posix.c:57: warning: ignoring ‘#pragma clang diagnostic’ [-Wunknown-pragmas]**

/usr/bin/gcc  -D_GNU_SOURCE -D_DEFAULT_SOURCE          -D_X86_64_ -DUNIX  -Dlinux      -g   -Wall -Werror-implicit-function-declaration    -Dminiz_EXPORTS -std=c99   -mtune=generic     -m64 -fPIC -I. -I../O.Common -I. -I. -I.. -I../../../dxpApp/handel/src -I../../../dxpApp/handel/libsinc-c -I../../../dxpApp/handel/miniz -I../../../include/compiler/gcc -I../../../include/os/Linux -I../../../include   -I/opt/epics/base-7.0.6.1/../modules/support/include   -I/opt/epics/base-7.0.6.1/../modules/support/seq-2-2-9/include    -I/opt/epics/base-7.0.6.1/include/compiler/gcc -I/opt/epics/base-7.0.6.1/include/os/Linux -I/opt/epics/base-7.0.6.1/include    -I../../../dxpApp/handel/inc -I../../../dxpApp/handel/sincSrc -I../../../dxpApp/handel/miniz    -c ../../../dxpApp/handel/src/handel_md_threads_posix.c
../../../dxpApp/handel/src/handel_md_threads_posix.c:57: warning: ignoring ‘#pragma clang diagnostic’ [-Wunknown-pragmas]
   57 | #pragma clang diagnostic ignored "-Wthread-safety-analysis"
      | 
/usr/bin/ar -rc    libhandelSITORO.a    falconx_mm.o falconxn_psl.o handel.o handel_dbg.o handel_detchan.o handel_dyn_default.o handel_dyn_detector.o handel_dyn_firmware.o handel_dyn_module.o handel_error.o handel_fdd_shim.o handel_file.o handel_log.o handel_run_control.o handel_run_params.o handel_sort.o handel_system.o md_shim.o psl.o xia_assert.o xia_file.o xia_sio.o api.o base64.o blocking.o command.o decode.o encapsulation.o encode.o readmessage.o protobuf-c.o request.o sinc.pb-c.o socket.o miniz.o miniz_tdef.o miniz_tinfl.o handel_md_threads_posix.o 
/usr/bin/ranlib libhandelSITORO.a
/usr/bin/g++ -o libhandelSITORO.so -shared -fPIC -Wl,-hlibhandelSITORO.so -L/opt/epics/modules/support/dxpSITORO-R1-2/lib/linux-x86_64-debug -L/opt/epics/base-7.0.6.1/lib/linux-x86_64-debug -Wl,-rpath,/opt/epics/modules/support/dxpSITORO-R1-2/lib/linux-x86_64-debug -Wl,-rpath,/opt/epics/base-7.0.6.1/lib/linux-x86_64-debug          -rdynamic -m64         falconx_mm.o falconxn_psl.o handel.o handel_dbg.o handel_detchan.o handel_dyn_default.o handel_dyn_detector.o handel_dyn_firmware.o handel_dyn_module.o handel_error.o handel_fdd_shim.o handel_file.o handel_log.o handel_run_control.o handel_run_params.o handel_sort.o handel_system.o md_shim.o psl.o xia_assert.o xia_file.o xia_sio.o api.o base64.o blocking.o command.o decode.o encapsulation.o encode.o readmessage.o protobuf-c.o request.o sinc.pb-c.o socket.o miniz.o miniz_tdef.o miniz_tinfl.o handel_md_threads_posix.o    -ldbRecStd -ldbCore -lca -lCom -Wl,-Bdynamic  -lpthread    -lm -lrt -ldl -lgcc
Installing shared library ../../../lib/linux-x86_64-debug/libhandelSITORO.so
Installing library ../../../lib/linux-x86_64-debug/libhandelSITORO.a
make[3]: Leaving directory '/opt/epics/modules/support/dxpSITORO-R1-2/dxpApp/handel/O.linux-x86_64-debug'
make[2]: Leaving directory '/opt/epics/modules/support/dxpSITORO-R1-2/dxpApp/handel'
make -C ./src install
make[2]: Entering directory '/opt/epics/modules/support/dxpSITORO-R1-2/dxpApp/src'
Makefile:44: /ADApp/commonDriverMakefile: No such file or directory
make[2]: *** No rule to make target '/ADApp/commonDriverMakefile'.  Stop.
make[2]: Leaving directory '/opt/epics/modules/support/dxpSITORO-R1-2/dxpApp/src'
make[1]: *** [/opt/epics/base-7.0.6.1/configure/RULES_DIRS:85: src.install] Error 2
make[1]: Leaving directory '/opt/epics/modules/support/dxpSITORO-R1-2/dxpApp'
make: *** [/opt/epics/base-7.0.6.1/configure/RULES_DIRS:85: dxpApp.install] Error 2

**Comment by MarkRivers** [comment]
It appears to me that you have not defined AREA_DETECTOR correctly in your configure/RELEASE file.  ADCORE is not defined when you build, but it gets defined in RELEASE_PRODS.local.

**Comment by anjohnson** [comment]
@LeeYangLBLBCS Here's how to solve EPICS build problems like this.

First look at the lines around the first actual error message reported by your build, which was this part:
```
make -C ./src install
make[2]: Entering directory '/opt/epics/modules/support/dxpSITORO-R1-2/dxpApp/src'
Makefile:44: /ADApp/commonDriverMakefile: No such file or directory
make[2]: *** No rule to make target '/ADApp/commonDriverMakefile'. Stop.
make[2]: Leaving directory '/opt/epics/modules/support/dxpSITORO-R1-2/dxpApp/src'
```
That points to line 44 of the Makefile in the dxpApp/src directory, which contains this:
```
include $(ADCORE)/ADApp/commonDriverMakefile
```
The error message says that make needs the file `/ADApp/commonDriverMakefile` which isn't likely to be where you would have installed areaDetector's ADCORE module, so the `$(ADCORE)` variable used on that line must be undefined (empty) in your installation. Pointers to dependent modules in EPICS builds _should_ be set by your local `configure/RELEASE` file, and in this case ADCore is part of AreaDetector and it's actually set by this include statement on line 23:
```
-include $(AREA_DETECTOR)/configure/RELEASE_PRODS.local
```
So either you don't have the `AREA_DETECTOR` variable set, or that module hasn't been installed/built properly, or the version of areaDetector you're using isn't compatible (which is much less likely though).

@MarkRivers Since areaDetector seems to be an essential dependency of this module, you might consider removing the `-` prefix from that `include` statement, which would cause the build to fail earlier.

**Comment by LeeYangLBLBCS** [comment]
yes, that fixed the problem. Though I don't understand why the commit change diffs shown in the following screen shot is not matching the latest code in this file; dxpSITORO-R1-2/dxpApp/handel/src/handel_md_threads_posix.c 
I thought I made some mistake with git clone.
![image](https://user-images.githubusercontent.com/15041332/193313020-919831b7-af07-43a5-8d29-6e226888cec2.png)

**Comment by MarkRivers** [comment]
That commit does match the latest code on the master branch.  
https://github.com/epics-modules/dxpSITORO/blob/127a7c485f640838fce47e297ad39d312ef1e6c3/dxpApp/handel/src/handel_md_threads_posix.c#L97

Are you using the master branch or R1-2, which your path implies?  R1-2 is from 2019 and there have been many changes since then, but no new release.

**Comment by LeeYangLBLBCS** [comment]
yes, the code does match now I'm looking at it again.
thanks for the help.
